version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - automated

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
      day: monday
      time: '09:00'
      timezone: Europe/Rome
    open-pull-requests-limit: 3
    labels:
      - ci
      - automated
