name: Markdown Lint
on:
  push:
    branches: [main, dev]
    paths: ["*.md", "**/*.md", ".markdownlint*"]
  pull_request:
    branches: [main]
    paths: ["*.md", "**/*.md", ".markdownlint*"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            !.github/**/*.md
            !LICENSE
            **/*.md
